In [1]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine

In [2]:
#connect to postgresSQL
engine = create_engine(
    
     "postgresql://postgres:postgres123@localhost:5432/malaria_db"
)

In [3]:
#load table
query = "SELECT * FROM malaria_dataset"

df = pd.read_sql(query, engine)

In [4]:
#creating a working copy
df_clean = df.copy()

In [5]:
# preview data
print(df_clean.head())

   participant_id  dose_num  dose_ordered  dose_start dose_start_time  \
0               1         1         250.0  2019-04-05            TRUE
1               1         2         250.0  2019-04-06            TRUE
2               1         3         250.0  2019-04-06            TRUE
3               1         4         250.0  2019-04-07            TRUE
4               2         1           NaN  2019-04-11            TRUE

     dose_end dose_end_time  dose_complete
0  2019-04-05          TRUE              1
1  2019-04-06          TRUE              1
2  2019-04-06          TRUE              1
3  2019-04-07          TRUE              1
4  2019-04-11         FALSE              1

In [6]:
#dataset structure
print(df_clean.info())

<class 'pandas.DataFrame'>
RangeIndex: 730 entries, 0 to 729
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   participant_id   730 non-null    int64
 1   dose_num         730 non-null    int64
 2   dose_ordered     729 non-null    float64
 3   dose_start       730 non-null    object
 4   dose_start_time  730 non-null    str
 5   dose_end         541 non-null    object
 6   dose_end_time    730 non-null    str
 7   dose_complete    730 non-null    int64
dtypes: float64(1), int64(3), object(2), str(2)
memory usage: 45.8+ KB
None

In [7]:
#verification to ensure copy created successfully
print(df_clean.shape)

(730, 8)

In [8]:
#standardizing column names
df_clean.columns = (
    df_clean.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

print(df_clean.columns)

Index(['participant_id', 'dose_num', 'dose_ordered', 'dose_start',
       'dose_start_time', 'dose_end', 'dose_end_time', 'dose_complete'],
      dtype='str')

In [9]:
#verifying column standardizatin
print(df_clean.columns.tolist())

['participant_id', 'dose_num', 'dose_ordered', 'dose_start', 'dose_start_time', 'dose_end', 'dose_end_time', 'dose_complete']

In [10]:
#missing values summary
missing_values = df_clean.isnull().sum()

#percentage missing
missing_percent = (
    df_clean.isnull().sum() / len(df_clean)
) *100

missing_summary = pd.DataFrame({
    "missing_count": missing_values,
    "missing_percent": missing_percent
})

missing_summary.sort_values(
    by="missing_percent",
    ascending=False)

                 missing_count  missing_percent
dose_end                   189        25.890411
dose_ordered                 1         0.136986
dose_num                     0         0.000000
participant_id               0         0.000000
dose_start                   0         0.000000
dose_start_time              0         0.000000
dose_end_time                0         0.000000
dose_complete                0         0.000000

In [11]:
#verification of missing summary
missing_summary.head()

                 missing_count  missing_percent
participant_id               0         0.000000
dose_num                     0         0.000000
dose_ordered                 1         0.136986
dose_start                   0         0.000000
dose_start_time              0         0.000000

In [12]:
#count duplicates
duplicate_count = df_clean.duplicated().sum()

print("Duplicated rows:", duplicate_count)

#remove duplicates
df_clean = df_clean.drop_duplicates()

"New shape:", df_clean.shape

Duplicated rows: 0

('New shape:', (730, 8))

In [13]:
#converting numeric columns
numeric_cols = [
    "dose_num",
    "dose_ordered"
]

for col in numeric_cols:
    if col in df_clean.columns:
        df_clean[col] = pd.to_numeric(
            df_clean[col],
            errors="coerce"
        )

In [14]:
#convert date columns
date_cols = [
    "dose_start",
    "dose_end"
]

for col in date_cols:
    if col in df_clean.columns:
        df_clean[col] = pd.to_datetime(
            df_clean[col],
            errors="coerce"
        )

In [15]:
#confirm datatype conversion
df_clean.dtypes

participant_id             int64
dose_num                   int64
dose_ordered             float64
dose_start         datetime64[s]
dose_start_time              str
dose_end           datetime64[s]
dose_end_time                str
dose_complete              int64
dtype: object

In [16]:
#standardizing time formatting
time_cols = [
    "dose_start_time",
    "dose_end_time"
]

for cols in time_cols:
    if col in df_clean.columns:
        df_clean[col] = pd.to_datetime(
            df_clean[col],
            errors="coerce"
        ).dt.time

df_clean[time_cols].head()

  dose_start_time dose_end_time
0            TRUE          TRUE
1            TRUE          TRUE
2            TRUE          TRUE
3            TRUE          TRUE
4            TRUE         FALSE

In [17]:
#checking for failed cnversion
for col in time_cols:
   print(col, df_clean[col].isnull().sum())

dose_start_time 0
dose_end_time 0

In [18]:
for col in time_cols:
    print(col, df_clean[col].unique()[:10])

dose_start_time <StringArray>
['TRUE', 'FALSE']
Length: 2, dtype: str
dose_end_time <StringArray>
['TRUE', 'FALSE']
Length: 2, dtype: str

In [19]:
#identifying object columns
text_cols = df_clean.select_dtypes(
    include=["object", "string"]
).columns

#standardize formating
for col in text_cols:
    df_clean[col] = (
        df_clean[col]
        .astype(str)
        .str.strip()
        .str.lower()
    )

print(df_clean[text_cols].head())

  dose_start_time dose_end_time
0            true          true
1            true          true
2            true          true
3            true          true
4            true         false

In [20]:
#check unique values after cleaning
for cols in text_cols:
    print(f"\nColumn: {col}")
    print(df_clean[col].unique()[:10])

Column: dose_end_time
<StringArray>
['true', 'false']
Length: 2, dtype: str

Column: dose_end_time
<StringArray>
['true', 'false']
Length: 2, dtype: str

In [21]:
#validation example
if "dose_complete" in df_clean.columns:
    print(df_clean["dose_complete"].value_counts(dropna=False))

dose_complete
1    730
Name: count, dtype: int64

In [22]:
#check unique values
df_clean["dose_complete"].unique()

array([1])

In [23]:
# Detect negative values
for col in numeric_cols:
    if col in df_clean.columns:
        invalid_count = (df_clean[col] < 0).sum()

        print(f"{col} negative values:", invalid_count)

dose_num negative values: 0
dose_ordered negative values: 0

In [24]:
# Display invalid rows if they exist
for col in numeric_cols:
    invalid_rows = df_clean[df_clean[col] < 0]

    print(invalid_rows[[col]].head())

Empty DataFrame
Columns: [dose_num]
Index: []
Empty DataFrame
Columns: [dose_ordered]
Index: []

In [25]:
# Check invalid date sequences
invalid_dates = df_clean[
    df_clean["dose_end"] < df_clean["dose_start"]
]

print("Invalid date rows:", len(invalid_dates))

Invalid date rows: 0

In [26]:
# Preview problematic rows
print(
    invalid_dates[
        ["participant_id",
         "dose_start",
         "dose_end"]
    ].head()
)

Empty DataFrame
Columns: [participant_id, dose_start, dose_end]
Index: []

In [27]:
#outlier detection
for col in numeric_cols:

    if col in df_clean.columns:

        q1 = df_clean[col].quantile(0.25)
        q3 = df_clean[col].quantile(0.75)

        iqr = q3 - q1

        lower_bound = q1 - (1.5 * iqr)
        upper_bound = q3 + (1.5 * iqr)

        outliers = df_clean[
            (df_clean[col] < lower_bound) |
            (df_clean[col] > upper_bound)
        ]

        print(f"\n{col}")
        print("Outliers:", len(outliers))

dose_num
Outliers: 2

dose_ordered
Outliers: 3

In [28]:
#preview outlier rows
print(outliers.head())

     participant_id  dose_num  dose_ordered dose_start dose_start_time  \
712             192         1         360.0 2019-12-25            true
713             192         2         360.0 2019-12-25            true
714             192         3         360.0 2019-12-26            true

    dose_end dose_end_time  dose_complete
712      NaT          true              1
713      NaT          true              1
714      NaT          true              1

In [29]:
# Create duration column
df_clean["treatment_duration_days"] = (
    df_clean["dose_end"] -
    df_clean["dose_start"]
).dt.days

print(
    df_clean[
        ["dose_start",
         "dose_end",
         "treatment_duration_days"]
    ].head()
)

  dose_start dose_end  treatment_duration_days
0 2019-04-05      NaT                      NaN
1 2019-04-06      NaT                      NaN
2 2019-04-06      NaT                      NaN
3 2019-04-07      NaT                      NaN
4 2019-04-11      NaT                      NaN

In [30]:
#checking the number of missing end dates
df_clean["dose_end"].isnull().sum()

np.int64(730)

In [31]:
#inspecting dose end columns
df["dose_end"].head()

0    2019-04-05
1    2019-04-06
2    2019-04-06
3    2019-04-07
4    2019-04-11
Name: dose_end, dtype: object

In [32]:
#reseting a clean copy
df_clean = df.copy()

In [33]:
#reconverting dates
df_clean["dose_end"] = pd.to_datetime(
    df_clean["dose_end"],
    errors="coerce"
)

df_clean["dose_start"] = pd.to_datetime(
    df_clean["dose_start"],
    errors="coerce"
)

In [34]:
#verifying verification done
df_clean[["dose_start", "dose_end"]].head()

  dose_start   dose_end
0 2019-04-05 2019-04-05
1 2019-04-06 2019-04-06
2 2019-04-06 2019-04-06
3 2019-04-07 2019-04-07
4 2019-04-11 2019-04-11

In [35]:
#rerunning the treatment duratin
# Create duration column
df_clean["treatment_duration_days"] = (
    df_clean["dose_end"] -
    df_clean["dose_start"]
).dt.days

In [36]:
#verifying the duration time
df_clean[
    [
        "dose_start",
        "dose_end",
        "treatment_duration_days"
    ]
].head()

  dose_start   dose_end  treatment_duration_days
0 2019-04-05 2019-04-05                      0.0
1 2019-04-06 2019-04-06                      0.0
2 2019-04-06 2019-04-06                      0.0
3 2019-04-07 2019-04-07                      0.0
4 2019-04-11 2019-04-11                      0.0

In [37]:
df_clean["treatment_duration_days"].value_counts()

treatment_duration_days
 0.0     534
 1.0       5
 2.0       1
-20.0      1
Name: count, dtype: int64

In [38]:
#inspecting invalid rows
df_clean[
    df_clean["treatment_duration_days"] < 0
]

,participant_id,dose_num,dose_ordered,dose_start,dose_start_time,dose_end,dose_end_time,dose_complete,treatment_duration_days
258,68,1,123.800003,2019-07-28,TRUE,2019-07-08,TRUE,1,-20.0

In [39]:
# Check summary statistics
print(
    df_clean[
        "treatment_duration_days"
    ].describe()
)

count    541.000000
mean      -0.024030
std        0.869959
min      -20.000000
25%        0.000000
50%        0.000000
75%        0.000000
max        2.000000
Name: treatment_duration_days, dtype: float64

In [40]:
#fixing invalid dates
start_date = df_clean.loc[258, "dose_start"]

end_date = df_clean.loc[258, "dose_end"]

df_clean.loc[258, "dose_start"] = end_date

df_clean.loc[258, "dose_end"] = start_date

In [41]:
#recalculating the treatment duration
df_clean["treatment_duration_days"] = (
    df_clean["dose_end"] -
    df_clean["dose_start"]
).dt.days

In [42]:
#verificatin of the fix
df_clean.loc[
    258,
    [
        "dose_start",
        "dose_end",
        "treatment_duration_days"
    ]
]

dose_start                 2019-07-08 00:00:00
dose_end                   2019-07-28 00:00:00
treatment_duration_days                   20.0
Name: 258, dtype: object

In [43]:
print(df_clean.info())

print(df_clean.isnull().sum())

print(df_clean.describe(include="all"))

<class 'pandas.DataFrame'>
RangeIndex: 730 entries, 0 to 729
Data columns (total 9 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   participant_id           730 non-null    int64
 1   dose_num                 730 non-null    int64
 2   dose_ordered             729 non-null    float64
 3   dose_start               730 non-null    datetime64[s]
 4   dose_start_time          730 non-null    str
 5   dose_end                 541 non-null    datetime64[s]
 6   dose_end_time            730 non-null    str
 7   dose_complete            730 non-null    int64
 8   treatment_duration_days  541 non-null    float64
dtypes: datetime64[s](2), float64(2), int64(3), str(2)
memory usage: 51.5 KB
None
participant_id               0
dose_num                     0
dose_ordered                 1
dose_start                   0
dose_start_time              0
dose_end                   189
dose_end_time                0
dose_complete                0
treatment_duration_days    189
dtype: int64
        participant_id    dose_num  dose_ordered           dose_start  \
count       730.000000  730.000000    729.000000                  730
unique             NaN         NaN           NaN                  NaN
top                NaN         NaN           NaN                  NaN
freq               NaN         NaN           NaN                  NaN
mean         95.223288    2.423288    163.773470  2019-08-21 12:43:23
min           1.000000    1.000000     23.500000  2019-04-05 00:00:00
25%          48.000000    1.000000    120.000000  2019-07-06 06:00:00
50%          94.000000    2.000000    175.000000  2019-08-18 00:00:00
75%         142.000000    3.000000    210.000000  2019-09-30 18:00:00
max         197.000000    8.000000    360.000000  2019-12-30 00:00:00
std          55.655720    1.133239     68.229778                  NaN

       dose_start_time             dose_end dose_end_time  dose_complete  \
count              730                  541           730          730.0
unique               2                  NaN             2            NaN
top               TRUE                  NaN          TRUE            NaN
freq               710                  NaN           538            NaN
mean               NaN  2019-08-17 22:42:48           NaN            1.0
min                NaN  2019-04-05 00:00:00           NaN            1.0
25%                NaN  2019-06-30 00:00:00           NaN            1.0
50%                NaN  2019-08-13 00:00:00           NaN            1.0
75%                NaN  2019-09-22 00:00:00           NaN            1.0
max                NaN  2019-12-30 00:00:00           NaN            1.0
std                NaN                  NaN           NaN            0.0

        treatment_duration_days
count                541.000000
unique                      NaN
top                         NaN
freq                        NaN
mean                   0.049908
min                    0.000000
25%                    0.000000
50%                    0.000000
75%                    0.000000
max                   20.000000
std                    0.868857

In [44]:
# Confirm final dataset shape
print(df_clean.shape)

# Confirm duplicate removal
print(df_clean.duplicated().sum())

(730, 9)
0

In [45]:
df_clean.to_sql(
    "malaria_cleaned",
    engine,
    if_exists="replace",
    index=False
)

730

In [46]:
#verification of export
test_df = pd.read_sql(
    "SELECT * FROM malaria_cleaned",
    engine
)

In [47]:
#preview
print(test_df.head())

   participant_id  dose_num  dose_ordered dose_start dose_start_time  \
0               1         1         250.0 2019-04-05            TRUE
1               1         2         250.0 2019-04-06            TRUE
2               1         3         250.0 2019-04-06            TRUE
3               1         4         250.0 2019-04-07            TRUE
4               2         1           NaN 2019-04-11            TRUE

    dose_end dose_end_time  dose_complete  treatment_duration_days
0 2019-04-05          TRUE              1                      0.0
1 2019-04-06          TRUE              1                      0.0
2 2019-04-06          TRUE              1                      0.0
3 2019-04-07          TRUE              1                      0.0
4 2019-04-11         FALSE              1                      0.0

In [48]:
print(test_df.shape)

(730, 9)

In [49]:
print(df_clean.shape)

(730, 9)